name: Scrape BPH hearing results

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Node dependencies
        run: npm install
      - name: Run scripts
        run: node scrape.mjs
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add hearing-results.json
          git pull origin $GITHUB_REF
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
